drop table if exists hit_requests;

CREATE TABLE IF NOT EXISTS hit_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app VARCHAR(30),
    uri VARCHAR(100),
    ip VARCHAR(20),
    date_time TIMESTAMP WITHOUT TIME ZONE
);