version: '3.8'
services:
  stats-server:
    build: ./statistics-module/service
    image: stats-image
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_POSTGRES_USER=root
      - SPRING_DATASOURCE_POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


  ewm-service:
    build: ./main-service-module
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"